### ISSUE TITLE
Error when Write Nessus_Generate_Activation_Code.py

### ISSUE THREAD

**Issue by Sajibekanti** [umarfarook882/Nessus-Home-Activation-Key-Generation#1]
python ./Nessus_Activation_Code.py 
==================================================================
            Generate Multiple Nessus Activation code                       
   Don't misuse this script other then for Pentesting purpose              
                      By:Fools of Security :)     
==================================================================
Traceback (most recent call last):
  File "./Nessus_Activation_Code.py", line 69, in <module>
    nessus_activation()
  File "./Nessus_Activation_Code.py", line 19, in nessus_activation
    email = tmp.get_email_address()  
  File "/usr/local/lib/python2.7/dist-packages/tempmail.py", line 66, in get_email_address
    available_domains = self.available_domains
  File "/usr/local/lib/python2.7/dist-packages/tempmail.py", line 35, in available_domains
    req = requests.get(url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='api.temp-mail.ru', port=80): Max retries exceeded with url: /request/domains/format/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f29eccf17d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

**Comment by evarot** [comment]
https://github.com/CITGuru/tempmail
