### ISSUE TITLE
KeyError: 3 on Nessus_Activation

### ISSUE THREAD

**Issue by armdn** [umarfarook882/Nessus-Home-Activation-Key-Generation#3]
=================================================================
            Generate Multiple Nessus Activation code                       
   Don't misuse this script other then for Pentesting purpose              
                      By:Fools of Security :)     
==================================================================
Traceback (most recent call last):
  File "Nessus_Activation_Code.py", line 69, in <module>
    nessus_activation()
  File "Nessus_Activation_Code.py", line 19, in nessus_activation
    email = tmp.get_email_address()  
  File "/usr/local/lib/python3.8/dist-packages/tempmail.py", line 68, in get_email_address
    self.domain = random.choice(available_domains)
  File "/usr/lib/python3.8/random.py", line 291, in choice
    return seq[i]
KeyError: 3

**Comment by wickedrifter** [comment]
Same error I got
